name = "GIFImages"
uuid = "7064036c-d33e-4a25-b247-cf6150d8ad81"
authors = ["Ashwani Rathee <ab669522@gmail.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Giflib_jll = "59f7168a-df46-5410-90c8-f2779963d0ec"
Noise = "81d43f40-5267-43b7-ae1c-8b967f377efa"
libgifextra_jll = "d7c3d077-fdb7-5318-9663-3e6817e0e281"

[compat]
julia = "1.7"
CEnum = "0.4.2"
ColorTypes = "0.11.3"
ColorVectorSpace = "0.9.9"
FileIO = "1.14.0"
FixedPointNumbers = "0.8.4"
Giflib_jll = "5.2.1"
libgifextra_jll = "0.0.1"